import { test as base, type Page } from "@playwright/test";

// ── Storage State Paths ───────────────────────────────────────────────────────
// These are generated by auth.setup.ts and admin.setup.ts.

export const AUTH_STORAGE_PATH = "e2e/.auth/user.json";
export const ADMIN_STORAGE_PATH = "e2e/.auth/admin.json";

// ── Test Fixtures ─────────────────────────────────────────────────────────────
//
// Extends the base Playwright test with authenticated page contexts.
// Use `authenticatedPage` to get a page logged in as a regular user,
// and `adminPage` to get a page logged in as an admin.

interface Fixtures {
  /** Page logged in as a regular user (uses auth storage state). */
  authenticatedPage: Page;
  /** Page logged in as an admin user. */
  adminPage: Page;
}

export const test = base.extend<Fixtures>({
  authenticatedPage: async ({ browser }, use) => {
    const context = await browser.newContext({
      storageState: AUTH_STORAGE_PATH,
    });
    const page = await context.newPage();
    await use(page);
    await context.close();
  },

  adminPage: async ({ browser }, use) => {
    const context = await browser.newContext({
      storageState: ADMIN_STORAGE_PATH,
    });
    const page = await context.newPage();
    await use(page);
    await context.close();
  },
});

export { expect } from "@playwright/test";
